### ISSUE TITLE
Sharing repository rights

### ISSUE THREAD

**Issue by TGuillerme** [kanead/Scavenger-Review#2]
Hey Adam,

I thought it might facilitate the collaborative work if you put us as **collaborators** on the project so we can edit files without sending pull requests all the time (unless you don't mind dealing with the pull requests spams - in this case ignore this issue).

You can do that by clicking on the followings:
`Settings` (in the navigation bar on top of the page) > `Collaborators` > _our GitHub names_ in the `add collaborators` box and then click the box

Up to you boss!:foggy::blowfish::cd:

**Comment by kanead** [comment]
Done, welcome aboard
